InvolaEcommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    # API base url
    path("api/", include("InvolaEcommerce.api_router"))
]

products/urls.py
from django.urls import path, include
from products.views import HomeView, CoffeeMachineView, CoffeePodView

app_name = 'products'

urlpatterns = [
    path('', view=HomeView.as_view(), name='home'),
    path('coffee_machine/', view=CoffeeMachineView.as_view(), name='coffee_machine_list'),
    path('coffee_pod/', view=CoffeePodView.as_view(), name='coffee_pod_list'),
]

products/models.py
from django.db import models


class CoffeeMachine(models.Model):
    product_name = models.CharField(max_length=256)
    product_type_choices = (
        ("COFFEE_MACHINE_LARGE", "COFFEE MACHINE LARGE"),
        ("COFFEE_MACHINE_SMALL", "COFFEE MACHINE SMALL"),
        ("ESPRESSO_MACHINE", "ESPRESSO MACHINE"),
    )
    product_type = models.CharField(choices=product_type_choices, max_length=100)

    model_type_choices = (
        ("base_model", "Base Model"),
        ("premium_model", "Premium Model"),
        ("deluxe_model", "Deluxe Model"),
    )
    model_type = models.CharField(choices=model_type_choices, max_length=100)

    water_line_compatible = models.BooleanField(default=True)

    def __str__(self):
        return self.product_name


class CoffeePod(models.Model):
    product_name = models.CharField(max_length=256)

    product_type_choices = (
        ("COFFEE_POD_LARGE", "COFFEE POD LARGE"),
        ("COFFEE_POD_SMALL", "COFFEE POD SMALL"),
        ("ESPRESSO_POD", "ESPRESSO POD"),
    )
    product_type = models.CharField(choices=product_type_choices, max_length=100)

    coffee_flavor_choices = (
        ("COFFEE_FLAVOR_VANILLA", "VANILLA"),
        ("COFFEE_FLAVOR_CARAMEL", "CARAMEL"),
        ("COFFEE_FLAVOR_PSL", "PSL"),
        ("COFFEE_FLAVOR_MOCHA", "MOCHA"),
        ("COFFEE_FLAVOR_HAZELNUT", "HAZELNUT"),
    )
    coffee_flavor = models.CharField(choices=coffee_flavor_choices, max_length=100)

    pack_size_choices = (
        (12, "1 dozen"),
        (36, "3 dozen"),
        (60, "5 dozen"),
        (84, "7 dozen"),
    )
    pack_size = models.PositiveIntegerField(choices=pack_size_choices)

    def __str__(self):
        return self.product_name

products/api/views.py
from rest_framework import permissions, status, serializers, viewsets

from rest_framework.decorators import (
    action,
    api_view,
    permission_classes,
    renderer_classes,
)

from rest_framework.renderers import (
    JSONRenderer,
    TemplateHTMLRenderer,
    BrowsableAPIRenderer,
    StaticHTMLRenderer,
)
from rest_framework.request import Request
from rest_framework.response import Response

from json import dumps, loads
from products.models import CoffeePod, CoffeeMachine


@api_view(["GET"])
# @permission_classes([permissions.IsAuthenticated])
@renderer_classes([JSONRenderer, BrowsableAPIRenderer])
def coffee_machine_data(request: Request):
    result = {}
    try:
        qs = CoffeeMachine.objects.all().values()

        # product type filter
        product_type = request.query_params.get("product_type", "")
        if product_type:
            qs = qs.filter(product_type=product_type)

        # water line filter
        water_line = request.query_params.get("water_line", "")
        if water_line == "true":
            qs = qs.filter(water_line_compatible=True)
        elif water_line == "false":
            qs = qs.filter(water_line_compatible=False)

        result["coffee_machines"] = qs
        return Response(status=status.HTTP_200_OK, data=result)
    except Exception as e:
        return Response(status=status.HTTP_500_INTERNAL_SERVER_ERROR, data={"error in coffee machines": f"{e}"})\



@api_view(["GET"])
# @permission_classes([permissions.IsAuthenticated])
@renderer_classes([JSONRenderer, BrowsableAPIRenderer])
def coffee_pod_data(request: Request):
    result = {}
    try:
        qs = CoffeePod.objects.all().values()

        # product type filter
        product_type = request.query_params.get("product_type", "")
        if product_type:
            qs = qs.filter(product_type=product_type)

        # coffee flavor filter
        coffee_flavor = request.query_params.get("coffee_flavor", "")
        if coffee_flavor:
            qs = qs.filter(coffee_flavor=coffee_flavor)

        # pack size filter
        pack_size = request.query_params.get("pack_size", "")
        if pack_size:
            qs = qs.filter(pack_size=pack_size)

        result["coffee_pods"] = qs
        return Response(status=status.HTTP_200_OK, data=result)
    except Exception as e:
        return Response(status=status.HTTP_500_INTERNAL_SERVER_ERROR, data={"error in coffee machines": f"{e}"})

products/views.py
from django.shortcuts import render

from django.views.generic import RedirectView, UpdateView, ListView, TemplateView, CreateView, DetailView
from django.utils.translation import ugettext_lazy as _
from django.conf.urls import url
from django.urls import reverse, reverse_lazy


class HomeView(TemplateView):
    template_name = "home.html"
    # bread_crumbs = [_("Inovola")]
    page_title = _("Home")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context["bread_crumbs"] = self.bread_crumbs
        context["page_title"] = self.page_title
        return context


class CoffeeMachineView(TemplateView):
    template_name = "pages/c_m.html"
    bread_crumbs = [_("Inovola"), _("Coffee Machine")]
    page_title = _("Coffee Machines")
    coffee_machine_api_url: url = reverse_lazy("api:coffee_machine_data")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["bread_crumbs"] = self.bread_crumbs
        context["page_title"] = self.page_title
        context["coffee_machine_api_url"] = self.coffee_machine_api_url
        return context


class CoffeePodView(TemplateView):
    template_name = "pages/c_p.html"
    bread_crumbs = [_("Inovola"), _("Coffee Pod")]
    page_title = _("Coffee Pods")
    coffee_pod_api_url: url = reverse_lazy("api:coffee_pod_data")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["bread_crumbs"] = self.bread_crumbs
        context["page_title"] = self.page_title
        context["coffee_pod_api_url"] = self.coffee_pod_api_url
        return context

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
       <!--  Meta data   -->
      <meta charset="UTF-8">
      <meta http-equiv="x-ua-compatible" content="ie=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="description" content="">
      <meta name="author" content="">

      <!--  Title    -->
      <title>Inovola- {% block title %}{% endblock title %}</title>


      <!-- Css Libs   -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />

      <!--  css    -->
      <link rel="stylesheet" href="{% static 'css/base.css' %}" />
      {% block extra_css %}{% endblock %}
</head>
<body>

      {% block navbar %}
          {% include 'partials/nav.html' %}
      {% endblock %}
      {% block sidebar %}
          {% include 'partials/sidebar.html' %}
      {% endblock %}
      <div class="content-wrapper container-fluid ml-0">

        <!--  Header-->
        {% block header %}{% endblock %}

        <div class="container-fluid">
            {% block content %}{% endblock%}
        </div>


      </div>





    <!--  Scripts  -->
    <script
			  src="https://code.jquery.com/jquery-3.5.1.js"
			  integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
			  crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    {% block extra_javascript %}{% endblock %}
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock%}

{% block header %}
    <div class="row " style="justify-content: flex-end;">
      <div class="col-4">
        <div class="page-title-box">
          {% if bread_crumbs %}
            <div class="page-title-right">
              <ol class="breadcrumb m-0" style="    justify-content: flex-end;">
                {% for bread_crumb in bread_crumbs %}
                  <li class="breadcrumb-item">{{ bread_crumb }}</li>
                {% endfor %}
              </ol>
            </div>
          {% endif %}

        </div>
      </div>
    </div>
    <div class="row mt-2">
        <div class="col-12">
          <div class="">
            <div style="float:left">
            <h4 class="page-title">{{ page_title }}</h4>
            </div>
          </div>
        </div>
    </div>

    <hr>
{% endblock %}

{% block content %}




{% endblock %}

templates/pages/c_m.html
{% extends "base.html" %}

{% block title %}Coffee Machine{% endblock%}

{% block header %}
    <div class="row " style="justify-content: flex-end;">
      <div class="col-4">
        <div class="page-title-box">
          {% if bread_crumbs %}
            <div class="page-title-right">
              <ol class="breadcrumb m-0" style="    justify-content: flex-end;">
                {% for bread_crumb in bread_crumbs %}
                  <li class="breadcrumb-item">{{ bread_crumb }}</li>
                {% endfor %}
              </ol>
            </div>
          {% endif %}

        </div>
      </div>
    </div>
    <div class="row mt-2">
        <div class="col-12">
          <div class="">
            <div style="float:left">
            <h4 class="page-title">{{ page_title }}</h4>
            </div>
          </div>
        </div>
    </div>

    <hr>
{% endblock %}

{% block content %}

            <div class="row">
              <div class="col-xl-3">
                <h4>Filters</h4>
              </div>
            </div>
            <div class="row" id="filters">
              <div class="col-xl-2">
                  <select class="custom-select" id="product_type">
                      <option disabled selected hidden>Select Product Type</option>
                      <option value="">All</option>
                      <option value="COFFEE_MACHINE_LARGE">LARGE</option>
                      <option value="COFFEE_MACHINE_SMALL">SMALL</option>
                      <option value="ESPRESSO_MACHINE">ESPRESSO MACHINE</option>
                  </select>
              </div>
              <div class="col-xl-2">
                  <select class="custom-select" id="water_line_compatible">
                      <option disabled selected hidden>Select Water line</option>
                      <option value="">All</option>
                      <option value="true">Yes</option>
                      <option value="false">No</option>
                  </select>
              </div>
              <div class="col-xl-2">
                <button type="button" class="btn btn-primary waves-effect waves-light" id="submit_filter">Filter</button>
                <button type="button" class="btn btn-secondary waves-effect waves-light" id="reset_filter">Reset</button>
              </div>
            </div>

              <div class="row mt-3" id="coffee_machines_list" style="justify-content:center">
              </div>


{% endblock %}

{% block extra_javascript %}
<script>
    var coffee_machine_api_url = '{{coffee_machine_api_url}}';

    try{
        $.ajax({
            type: "GET",
            dataType: "json",
            url: coffee_machine_api_url,
            success: function(data){
                if (data){
                  if (!jQuery.isEmptyObject(data['coffee_machines'])){
                    render_coffee_machine_cards(data['coffee_machines'])
                  }
                }
            }
        });
    }catch(error){
        console.log(error)
    };

    // submit filter
    $('#submit_filter').on('click', function(){
        try{
          var product_type = $('#product_type').val()
          if (product_type){
            coffee_machine_filter_api_url = coffee_machine_api_url +  `?product_type=${product_type}`
          }else{
            coffee_machine_filter_api_url = coffee_machine_api_url+'?'
          }
          var water_line_compatible = $('#water_line_compatible').val()
          if (water_line_compatible){
            coffee_machine_filter_api_url = coffee_machine_filter_api_url +  `&water_line=${water_line_compatible}`
          }else{
            coffee_machine_filter_api_url = coffee_machine_filter_api_url
          }
          $.ajax({
              type: "GET",
              dataType: "json",
              url: coffee_machine_filter_api_url,
              success: function(data){
                try{
                  if (data){
                      if (!jQuery.isEmptyObject(data['coffee_machines'])){
                        render_coffee_machine_cards(data['coffee_machines']);
                      }else{
                        $('#coffee_machines_list').empty();
                        $('#coffee_machines_list').append('<div class="col-xl-5 text-muted">No Coffee Machines Found ..</div>')
                      }
                  }
                }catch(error){
                  console.log(error)
                };
              }
          });
        }catch(error){
          console.log(error)
        };
      });

      // reset filter
      $('#reset_filter').on('click', function(){
        try{
          $.ajax({
              type: "GET",
              dataType: "json",
              url: coffee_machine_api_url,
              success: function(data){
                try{
                  if (data){
                    if(data['coffee_machines']){
                        render_coffee_machine_cards(data['coffee_machines']);
                        $('#product_type :nth-child(1)').prop('selected', true);
                        $('#water_line_compatible :nth-child(1)').prop('selected', true);

                    }
                  }
                }catch(error){
                  console.log(error)
                };
              }
          });
        }catch(error){
          console.log(error)
        };
      });

    function render_coffee_machine_cards(data){
        if (!jQuery.isEmptyObject(data)){
            $('#coffee_machines_list').empty();
            for (var item of data){
                $('#coffee_machines_list').append(`
                    <div class="card mb-3 mt-3 col-sm-3 mr-2 ml-2" style="">
                      <div class="row no-gutters">
                        <div class="col-md-4">
                          <img src="https://imgaz1.staticbg.com/thumb/view/oaupload/ser1/banggood/images/3B/F4/bf29ad2d-4734-4f57-b1c9-dad5c497a1ae.png" height=165 class="card-img" alt="...">
                        </div>
                        <div class="col-md-8">
                          <div class="card-body">
                            <h5 class="card-title">Product: ${item['product_name']}</h5>
                            <p class="card-text">Type: `+ get_product_type(item['product_type'])+`</p>
                            <p class="card-text"><small class="text-muted">Water Line Compatible: `+get_water_compatible_icon(item['water_line_compatible'])+`</small></p>
                            <p class="card-text"><small class="text-muted">Model: `+format_string(item['model_type'])+`</small></p>
                          </div>
                        </div>
                      </div>
                    </div>
                `)

            }
        }
    }


    function get_product_type(slug){
        let productsTypes = {
            "COFFEE_MACHINE_SMALL" : "SMALL",
            "COFFEE_MACHINE_LARGE" : "LARGE",
            "ESPRESSO_MACHINE" : "ESPRESSO MACHINE",
        }

        if ( slug in  productsTypes){
            return productsTypes[slug]
        }else{
            return slug
        }
    }

    function get_water_compatible_icon(value){
        if (value){
            html = `<i class="fas fa-check-circle" style='color:green'></i>`
        }else{
            html = `<i class="fas fa-times-circle" style='color:red'></i>`
        }

        return html
    }

    function format_string(str){
        var commaReplacedStr = str.replace(/_/g, ' ');
        var uppercaseStr = commaReplacedStr.replace(/(?:^|\s)\S/g, function(a) { return a.toUpperCase(); });
        return uppercaseStr
    }

</script>
{% endblock %}

templates/pages/c_p.html
{% extends "base.html" %}

{% block title %}Coffee Pod{% endblock%}

{% block header %}
    <div class="row " style="justify-content: flex-end;">
      <div class="col-4">
        <div class="page-title-box">
          {% if bread_crumbs %}
            <div class="page-title-right">
              <ol class="breadcrumb m-0" style="    justify-content: flex-end;">
                {% for bread_crumb in bread_crumbs %}
                  <li class="breadcrumb-item">{{ bread_crumb }}</li>
                {% endfor %}
              </ol>
            </div>
          {% endif %}

        </div>
      </div>
    </div>
    <div class="row mt-2">
        <div class="col-12">
          <div class="">
            <div style="float:left">
            <h4 class="page-title">{{ page_title }}</h4>
            </div>
          </div>
        </div>
    </div>

    <hr>
{% endblock %}

{% block content %}

    <div class="row">
      <div class="col-xl-3">
        <h4>Filters</h4>
      </div>
    </div>
    <div class="row" id="filters">
      <div class="col-xl-2">
          <select class="custom-select" id="product_type">
              <option disabled selected hidden>Select Product Type</option>
              <option value="">All</option>
              <option value="COFFEE_POD_LARGE">LARGE</option>
              <option value="COFFEE_POD_SMALL">SMALL</option>
              <option value="ESPRESSO_POD">ESPRESSO POD</option>
          </select>
      </div>
      <div class="col-xl-2">
          <select class="custom-select" id="coffee_flavor">
              <option disabled selected hidden>Select Coffee Flavor</option>
              <option value="">All</option>
              <option value="COFFEE_FLAVOR_VANILLA">VANILLA</option>
              <option value="COFFEE_FLAVOR_CARAMEL">CARAMEL</option>
              <option value="COFFEE_FLAVOR_PSL">PSL</option>
              <option value="COFFEE_FLAVOR_MOCHA">MOCHA</option>
              <option value="COFFEE_FLAVOR_HAZELNUT">HAZELNUT</option>
          </select>
      </div>
      <div class="col-xl-2">
          <select class="custom-select" id="pack_size">
              <option disabled selected hidden>Select Pack Size</option>
              <option value="">All</option>
              <option value="12">1 dozen</option>
              <option value="36">3 dozen</option>
              <option value="60">5 dozen</option>
              <option value="84">7 dozen</option>
          </select>
      </div>
      <div class="col-xl-2">
        <button type="button" class="btn btn-primary waves-effect waves-light" id="submit_filter">Filter</button>
        <button type="button" class="btn btn-secondary waves-effect waves-light" id="reset_filter">Reset</button>
      </div>
    </div>

    <div class="row mt-3" id="coffee_pods_list" style="justify-content:center">
    </div>



{% endblock %}

{% block extra_javascript %}
<script>
    var coffee_pod_api_url = '{{coffee_pod_api_url}}';

    try{
        $.ajax({
            type: "GET",
            dataType: "json",
            url: coffee_pod_api_url,
            success: function(data){
                if (data){
                  if (!jQuery.isEmptyObject(data['coffee_pods'])){
                    render_coffee_pod_cards(data['coffee_pods'])
                  }
                }
            }
        });
    }catch(error){
        console.log(error)
    };

    // submit filter
    $('#submit_filter').on('click', function(){
        try{
          var product_type = $('#product_type').val()
          if (product_type){
            coffee_pod_filter_api_url = coffee_pod_api_url +  `?product_type=${product_type}`
          }else{
            coffee_pod_filter_api_url = coffee_pod_api_url+'?'
          }
          var coffee_flavor = $('#coffee_flavor').val()
          if (coffee_flavor){
            coffee_pod_filter_api_url = coffee_pod_filter_api_url +  `&coffee_flavor=${coffee_flavor}`
          }else{
            coffee_pod_filter_api_url = coffee_pod_filter_api_url
          }

          var pack_size = Number($('#pack_size').val());
          if (pack_size){
            coffee_pod_filter_api_url = coffee_pod_filter_api_url +  `&pack_size=${pack_size}`
          }else{
            coffee_pod_filter_api_url = coffee_pod_filter_api_url
          }
          $.ajax({
              type: "GET",
              dataType: "json",
              url: coffee_pod_filter_api_url,
              success: function(data){
                try{
                  if (data){
                      if (!jQuery.isEmptyObject(data['coffee_pods'])){
                        render_coffee_pod_cards(data['coffee_pods']);
                      }else{
                        $('#coffee_pods_list').empty();
                        $('#coffee_pods_list').append('<div class="col-xl-5 text-muted">No Coffee Pods Found ..</div>')
                      }
                  }
                }catch(error){
                  console.log(error)
                };
              }
          });
        }catch(error){
          console.log(error)
        };
      });

      // reset filter
      $('#reset_filter').on('click', function(){
        try{
          $.ajax({
              type: "GET",
              dataType: "json",
              url: coffee_pod_api_url,
              success: function(data){
                try{
                  if (data){
                    if(data['coffee_pods']){
                        render_coffee_pod_cards(data['coffee_pods']);
                        $('#product_type :nth-child(1)').prop('selected', true);
                        $('#coffee_flavor :nth-child(1)').prop('selected', true);
                        $('#pack_size :nth-child(1)').prop('selected', true);
                    }
                  }
                }catch(error){
                  console.log(error)
                };
              }
          });
        }catch(error){
          console.log(error)
        };
      });

    function render_coffee_pod_cards(data){
        if (!jQuery.isEmptyObject(data)){
            $('#coffee_pods_list').empty();
            for (var item of data){
                console.log(item)
                $('#coffee_pods_list').append(`
                    <div class="card mb-3 mt-3 col-sm-3 mr-2 ml-2" style="">
                      <div class="row no-gutters">
                        <div class="col-md-4">
                          <img src="https://lanecove.s3.ap-southeast-2.amazonaws.com/wp-content/uploads/2016/08/04232833/shutterstock_352068635.jpg" height=180 class="card-img" alt="...">
                        </div>
                        <div class="col-md-8">
                          <div class="card-body">
                            <h5 class="card-title">Product: ${item['product_name']}</h5>
                            <p class="card-text">Type: `+ get_product_type(item['product_type'])+`</p>
                            <p class="card-text"><small class="text-muted">Flavor: `+get_product_flavor(item['coffee_flavor'])+`</small></p>
                            <p class="card-text"><small class="text-muted">Pack Size: `+get_product_pack_size(item['pack_size'])+`</small></p>
                          </div>
                        </div>
                      </div>
                    </div>
                `)

            }
        }
    }


    function get_product_type(slug){
        let productsTypes = {
            "COFFEE_POD_SMALL" : "SMALL",
            "COFFEE_POD_LARGE" : "LARGE",
            "ESPRESSO_POD" : "ESPRESSO POD",
        }

        if ( slug in  productsTypes){
            return productsTypes[slug]
        }else{
            return slug
        }
    }

    function get_product_flavor(slug){
        let productsFlavors = {
            "COFFEE_FLAVOR_VANILLA" : "VANILLA",
            "COFFEE_FLAVOR_CARAMEL" : "CARAMEL",
            "COFFEE_FLAVOR_PSL" : "PSL",
            "COFFEE_FLAVOR_MOCHA" : "MOCHA",
            "COFFEE_FLAVOR_HAZELNUT" : "HAZELNUT",
        }

        if ( slug in  productsFlavors){
            return productsFlavors[slug]
        }else{
            return slug
        }
    }

    function get_product_pack_size(num){
        let productsPackSizes = {
            12 : "1 dozen",
            36 : "3 dozen",
            60 : "5 dozen",
            84 : "7 dozen",
        }

        if ( num in  productsPackSizes){
            return productsPackSizes[num]
        }else{
            return slug
        }
    }

</script>
{% endblock %}

templates/partials/nav.html
<!-- Image and text -->
<nav class="navbar fixed-top navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'products:home' %}">
    <img src="https://inovola.com/wp-content/uploads/2020/07/logo-with-shadow200.png" width="200" height="48" class="d-inline-block align-top" alt="Inovola" loading="lazy">

  </a>
</nav>

templates/partials/sidebar.html
<!-- Side navigation -->
<div class="sidenav">
  <a href="{% url 'products:coffee_machine_list' %}" style="font-size: 15pt;">Coffee Machines</a>
  <a href="{% url 'products:coffee_pod_list' %}" style="font-size: 15pt;">Coffee Pods</a>
</div>